objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGO_IDO_Personas__mdt.object
<CustomObject>
    <description>WHAT: Custom Metadata for storing IDs of hero records and demo personas. This is used for org configuration updates.
WHO: Brian Ricter | Q Branch
WHEN: 242.1</description>
    <fields>
        <fullName>Demo_Story__c</fullName>
        <label>Demo Story</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Crisis &amp; Trauma Support</fullName>
                    <default>true</default>
                    <label>Crisis &amp; Trauma Support</label>
                </value>
                <value>
                    <fullName>Employment</fullName>
                </value>
                <value>
                    <fullName>Food Access</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>This is the External Id of the record itself, not of this metadata entry.</description>
        <inlineHelpText>This is the External Id of the record itself, not of this metadata entry.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_Record__c</fullName>
        <label>Name of Record</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <label>Target Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ListView</fullName>
                    <default>true</default>
                    <label>ListView</label>
                </value>
                <value>
                    <fullName>Record</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>NGO IDO Personas</label>
    <pluralLabel>NGO IDO Personas</pluralLabel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/NGO_Base_RecentRecordCTRL.cls
public class NGO_Base_RecentRecordCTRL {
    public String demoStory {get; set;}
    
    public static void runEmployment() {
        
        getMetadata('Employment');
    }

        public static void runCrisisSupport() {
        
        getMetadata('Crisis & Trauma Support');
    }
    
    public static void getMetadata(String demoStory) {
        NGO_IDO_Personas__mdt[] personaList = [SELECT External_Id__c, Id, Name_of_Record__c, Sort_Order__c, Target_Type__c FROM NGO_IDO_Personas__mdt WHERE Demo_Story__c =: demoStory];
    	String favQuery = '';
        String recAccQuery = '';
        Account acc = new Account();
        ListView lv = new ListView();
        for (NGO_IDO_Personas__mdt a : personaList) {
            if (a.Target_Type__c == 'Record') {
                acc = [SELECT Id, Name FROM Account WHERE External_Id__c =: a.External_Id__c];
              //  User commUser = [SELECT id, ContactId, Contact.AccountId, External_Id__c FROM User WHERE Contact.AccountId =: acc.Id LIMIT 1]; 
              // commUser.External_Id__c = 'User.HeroPersona';
              //  update commUser;
            } else if (a.Target_Type__c == 'ListView') {
                System.debug('Adding a ListView is coming soon!');
            }
            favQuery = favQuery + '{"name": "'+a.Name_of_Record__c + '", "sortOrder": '+ a.Sort_Order__c +', "target": "'+acc.Id +'", "targetType": "Record"}';
        	recAccQuery = 'SELECT+Id+FROM+ACCOUNT+WHERE+Id=\''+acc.Id+'\'+FOR+VIEW';
        }
        setFavorites(favQuery);
        setRecentAccounts(recAccQuery);


    }
    
          public static PageReference redirect(){
            PageReference pageRef = new PageReference('/lightning/n/qbranch__Demo_Wizard');
            return pageRef;
        }


    
    public static void setRecentAccounts(String fullQuery) {
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
        String baseURL = URL.getOrgDomainUrl().toExternalForm();
        
        //req.setEndpoint('https://br-ngotso013123.my.salesforce.com/services/data/v59.0/query/?q=SELECT+Name+FROM+Account+LIMIT+1+FOR+VIEW');
        req.setEndpoint(baseURL + '/services/data/v59.0/query/?q='+fullQuery);
        req.setMethod('GET');
        req.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionId());
        
        try {
            res = http.send(req);
            System.debug(res.getBody());
        } catch (System.CalloutException e) {
            System.debug('Callout error: ' + e);
        }
    }
    
        public static void setFavorites(String fullQuery) {
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
        String baseURL = URL.getOrgDomainUrl().toExternalForm();

            
        req.setEndpoint(baseURL + '/services/data/v59.0/ui-api/favorites/');
        req.setMethod('POST');
        req.setHeader('Authorization', 'Bearer '+ UserInfo.getSessionId());
        req.setHeader('Content-Type', 'application/json');
        req.setBody(fullQuery);

        try {
            res = http.send(req);
            System.debug(res.getBody());
        } catch (System.CalloutException e) {
            System.debug('Callout error: ' + e);
        }
    }
    
}