objects/Benefit.object
<CustomObject>
    <fields>
        <fullName>NGO_CaseMan_Total_Attended__c</fullName>
        <label>Total Attended</label>
        <summarizedField>BenefitSchedule.NGO_CaseMan_Total_Attended__c</summarizedField>
        <summaryForeignKey>BenefitSchedule.BenefitId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NGO_CaseMan_Total_Unattended__c</fullName>
        <label>Total Unattended</label>
        <summarizedField>BenefitSchedule.NGO_CaseMan_Total_Unattended__c</summarizedField>
        <summaryForeignKey>BenefitSchedule.BenefitId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Absent_Benefit_Disbursements__c</fullName>
        <defaultValue>0</defaultValue>
        <description>For the specified Benefit, the count of BenefitDisbursement records where Status = &quot;Excused Absent&quot; or &quot;Unexcused Absent&quot;.</description>
        <inlineHelpText>For the specified Benefit, the count of BenefitDisbursement records where Status = &quot;Excused Absent&quot; or &quot;Unexcused Absent&quot;.</inlineHelpText>
        <label>Number of Absent Benefit Disbursements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Attended_Benefit_Disbursements__c</fullName>
        <defaultValue>0</defaultValue>
        <description>For the specified Benefit, the count of BenefitDisbursement records where Status = &quot;Attended&quot;.</description>
        <inlineHelpText>For the specified Benefit, the count of BenefitDisbursement records where Status = &quot;Attended&quot;.</inlineHelpText>
        <label>Number of Attended Benefit Disbursements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BenefitSchedule.object
<CustomObject>
    <fields>
        <fullName>NGO_CaseMan_Total_Attended__c</fullName>
        <label>Total Attended</label>
        <summarizedField>BenefitSession.NGO_CaseMan_Total_Attended__c</summarizedField>
        <summaryForeignKey>BenefitSession.BenefitScheduleId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NGO_CaseMan_Total_Unattended__c</fullName>
        <label>Total Unattended</label>
        <summarizedField>BenefitSession.NGO_CaseMan_Total_Unattended__c</summarizedField>
        <summaryForeignKey>BenefitSession.BenefitScheduleId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Absent_Benefit_Disbursements__c</fullName>
        <defaultValue>0</defaultValue>
        <description>For the specified BenefitSchedule, the count of BenefitDisbursement records where Status = &quot;Excused Absent&quot; or &quot;Unexcused Absent&quot;.</description>
        <inlineHelpText>For the specified BenefitSchedule, the count of BenefitDisbursement records where Status = &quot;Excused Absent&quot; or &quot;Unexcused Absent&quot;.</inlineHelpText>
        <label>Number of Absent Benefit Disbursements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Attended_Benefit_Disbursements__c</fullName>
        <defaultValue>0</defaultValue>
        <description>For the specified BenefitSchedule, the count of BenefitDisbursement records where Status = &quot;Attended&quot;.</description>
        <inlineHelpText>For the specified BenefitSchedule, the count of BenefitDisbursement records where Status = &quot;Attended&quot;.</inlineHelpText>
        <label>Number of Attended Benefit Disbursements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BenefitSession.object
<CustomObject>
    <fields>
        <fullName>NGO_CaseMan_Total_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NGO_CaseMan_Total_Unattended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Unattended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Absent_Benefit_Disbursements__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Absent Benefit Disbursements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Attended_Benefit_Disbursements__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Attended Benefit Disbursements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProgramEnrollment.object
<CustomObject>
    <fields>
        <fullName>Number_of_Absent_Benefit_Disbursements__c</fullName>
        <label>Number of Absent Benefit Disbursements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Attended_Benefit_Disbursements__c</fullName>
        <label>Number of Attended Benefit Disbursements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/NGO_CaseMan_BenDisbAttendance.cls
public class NGO_CaseMan_BenDisbAttendance {
    
    public static void updateBenefit(BenefitDisbursement bd) {
        BenefitAssignment ba = [SELECT Id, BenefitId FROM BenefitAssignment WHERE Id =: bd.BenefitAssignmentId LIMIT 1];
        Benefit ben = [SELECT Id FROM Benefit WHERE Id =: ba.BenefitId LIMIT 1];
        Integer absent = 0;
        Integer attended = 0;
        List<BenefitDisbursement> bdList = [SELECT Id, DisbursementStatus FROM BenefitDisbursement WHERE BenefitAssignment.BenefitId =: ben.Id];
        for (BenefitDisbursement loopBD : bdList) {
            if (loopBd.DisbursementStatus == 'Attended') {
                attended++;
            } else if (loopBd.DisbursementStatus == 'Unexcused Absent' || loopBd.DisbursementStatus == 'Excused Absent') {
                absent++;
            }
 
        }
                   
            ben.Number_of_Absent_Benefit_Disbursements__c = absent;
            ben.Number_of_Attended_Benefit_Disbursements__c = attended;
        update ben;
    }

    
        public static void updateBenefitSession(BenefitDisbursement bd) {
        BenefitSession bs = [SELECT Id, BenefitScheduleId FROM BenefitSession WHERE Id =: bd.BenefitSessionId LIMIT 1];
        Integer absent = 0;
        Integer attended = 0;
        List<BenefitDisbursement> bdList = [SELECT Id, DisbursementStatus FROM BenefitDisbursement WHERE BenefitSessionId =: bs.Id];
        for (BenefitDisbursement loopBD : bdList) {
            if (loopBd.DisbursementStatus == 'Attended') {
                attended++;
            } else if (loopBd.DisbursementStatus == 'Unexcused Absent' || loopBd.DisbursementStatus == 'Excused Absent') {
                absent++;
            }
 
        }
                   
           bs.NGO_CaseMan_Total_Unattended__c = absent;
           bs.NGO_CaseMan_Total_Attended__c = attended;
        update bs;
    }
    
        public static void updateBenefitSchedule(BenefitDisbursement bd) {
        BenefitSession bs = [SELECT Id, BenefitScheduleId FROM BenefitSession WHERE Id =: bd.BenefitSessionId LIMIT 1];
        BenefitSchedule bsched = [SELECT Id FROM BenefitSchedule WHERE Id =: bs.BenefitScheduleId LIMIT 1];
        Integer absent = 0;
        Integer attended = 0;
        List<BenefitDisbursement> bdList = [SELECT Id, DisbursementStatus FROM BenefitDisbursement WHERE BenefitSession.BenefitScheduleId =: bsched.Id];
        for (BenefitDisbursement loopBD : bdList) {
            if (loopBd.DisbursementStatus == 'Attended') {
                attended++;
            } else if (loopBd.DisbursementStatus == 'Unexcused Absent' || loopBd.DisbursementStatus == 'Excused Absent') {
                absent++;
            }
 
        }
                   
           bsched.Number_of_Absent_Benefit_Disbursements__c = absent;
           bsched.Number_of_Attended_Benefit_Disbursements__c = attended;
        update bsched;
    }
    
            public static void updateProgramEnrollment(BenefitDisbursement bd) {
        ProgramEnrollment pe = [SELECT Id FROM ProgramEnrollment WHERE Id =: bd.ProgramEnrollmentId LIMIT 1];
        Integer absent = 0;
        Integer attended = 0;
        List<BenefitDisbursement> bdList = [SELECT Id, DisbursementStatus FROM BenefitDisbursement WHERE ProgramEnrollmentId =: pe.Id];
        for (BenefitDisbursement loopBD : bdList) {
            if (loopBd.DisbursementStatus == 'Attended') {
                attended++;
            } else if (loopBd.DisbursementStatus == 'Unexcused Absent' || loopBd.DisbursementStatus == 'Excused Absent') {
                absent++;
            }
 
        }
                   
           pe.Number_of_Absent_Benefit_Disbursements__c = absent;
           pe.Number_of_Attended_Benefit_Disbursements__c = attended;
        update pe;
    }

}